sudo: required
language: node_js
node_js:
- 13
deploy:
  provider: heroku
  api_key:
    secure: hbwRuY5itDS0VWQPTO9WQ308Mb3xYNzX4hafWNr1cpC9Ku3hsaVxTZWtQE3Gz/PEoMQ7p42vsFNbD7MfV50jCH9zrI7nvMjTOuMelXhBz7vVmUZpVVlH5nze5cPbMpvXW/tV3RQch0Ll8bFjd56/GIxUm7RhVbMDerZkPM83V0E4UoLq8wwzos6Kk14jiG8oKeuDCc7G+TNTpmBPLfciDs95idvA2zUJ8JKAcj9rdnGZ/kU976QUODI6xlIbJj33c+Spryfhc4RAsV/3XcmcL5Hdp5kXr3Pq64h5NkWYBSoQZQxhuJK9ti6GlTJoRFSu6dzC18mUUOIAMBTMt9XI8OCd4DrbQrYK5PQsdFR+azukZlYgN/BbJI87wfLnNOsgn1KecfgeVnApqSHx2uJDf6tRwiyP6WYYs6CTXuj1kFOfBGKmk95WtQ8pg34HUeFebREXNQhToTQybPqoHyyNcvEmKY/r2fFEYtr2U+EB3UHH7c8GZMFXAwGZIcovTc8RBHxZRGdBDlTubUVZz5AQ9t/sXQ6g+mSAiaAWWgzK6ZNwF+0XtnJfINB4NOERVG4fcrvxYsPn0FNWBsLIGYOF1+5pKrKbD4HVqJJzK4is0o+e4UDQTxhKtyxGFAr50TAZWMTMRfRZK2ECx8UW2LfHriqsJJYsy7aTHR8OUgWpMq0=
  app:
    master: ancient-headland-32576
